<?php /* @var \Tingle\Pmeds\Block\Form\Fields\Select $block */ ?>
<?php $options = $block->getFormattedOptions() ?>
<div class="field name <?= $block->getIsRequiredAttribute() ?>">
    <label class="label" for="pmeds-question-<?= $block->getQuestionId() ?>"><span><?= $block->getQuestionTitle() ?></span></label>
    <select id="pmeds-question-<?= $block->getQuestionId() ?>" <?= $block->getIsRequiredAttribute() ?>
            class="input-text question-select">
        <option value=""></option>
        <?php foreach ($options as $key => $title): ?>
            <option value="<?= $key ?>"><?= $title ?></option>
        <?php endforeach; ?>
    </select>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Tingle_Pmeds/js/form/questions/answer": {
                "selector": "pmeds-question-<?= $block->getQuestionId() ?>",
                "answer": "<?php $block->getCorrectAnswer() ? $block->getCorrectAnswer() : null ?>"
            }
        }
    }
</script>