<?php /** @var \Tingle\Pmeds\Block\Form\Fields\Textarea $block */ ?>
<div class="field name <?= $block->getIsRequiredAttribute() ?>">
    <label class="label" for="<?= $block->getFieldIdAttribute() ?>"><span><?= $block->getQuestionTitle() ?></span></label>
    <div class="control">
        <textarea id="<?= $block->getFieldIdAttribute() ?>" name="pmeds-validate"
                  class="input-text question-textarea <?= $block->getIsRequiredAttribute() ?>" type="text"></textarea>
    </div>
</div>
