<?php /** @var \Tingle\Pmeds\Block\Form\Fields\Text $block */ ?>
<div class="field name <?= $block->getIsRequiredAttribute() ?>">
    <label class="label" for="pmeds-question-<?= $block->getQuestionId() ?>"><span><?= $block->getQuestionTitle() ?></span></label>
    <input id="pmeds-question-<?= $block->getQuestionId() ?>" <?= $block->getIsRequiredAttribute() ?> value="" class="input-text question-text" type="text" />
</div>