<?php /** @var \Tingle\Pmeds\Block\Form\Fields\TextArea $block */ ?>
<div class="field name <?= $block->getIsRequiredAttribute() ?>">
    <label class="label" for="pmeds-question-<?= $block->getQuestionId() ?>"><span><?= $block->getQuestionTitle() ?></span></label>

    <textarea id="pmeds-question-<?= $block->getQuestionId() ?>" <?= $block->getIsRequiredAttribute() ?>
              class="input-text question-textarea" type="text"></textarea>

</div>
